version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clinica_mullo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica_mullo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 