version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clinica_mullo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clinica_mullo
      MYSQL_USER: clinica_user
      MYSQL_PASSWORD: clinica_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 