version: '3.8'

services:
  frontend:
    container_name: clinica_mullo_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: clinica_mullo_backend
    build:
      context: ./backend-nest
      dockerfile: Dockerfile.backend.prod
    restart: always
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Hospital2024!
      - DB_DATABASE=clinica_mullo
      - JWT_SECRET=clinicaMullo2024SecretKey
      - JWT_EXPIRATION_TIME=86400
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: clinica_mullo_db
    environment:
      MYSQL_ROOT_PASSWORD: Hospital2024!
      MYSQL_DATABASE: clinica_mullo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: clinica_mullo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/www/certbot:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: clinica_mullo_certbot
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@clinicamullo.com --agree-tos --no-eff-email -d clinicamullo.com -d www.clinicamullo.com --force-renewal
    depends_on:
      - nginx

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 